import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { Sensor, ownedSettings } from './sensor.mjs';
import { readJSON, saveJSON } from './storage.mjs';

// Grants the airmouse group access to the one discovered BMI323 sensor and records the original
// ownership for restore. It also derives the service sandbox paths from discovery so the unit never
// hard-codes an IIO device index. Modes: `prepare` (install: grant and write the drop-in),
// no argument (ExecStartPre: grant and require the drop-in to match), `restore` (rollback).
if (process.getuid() !== 0) throw new Error('Installation requires root');
const base = process.env.AIRMOUSE_BASE ?? '/mnt/data/airmouse';
const unitDir = process.env.AIRMOUSE_UNIT_DIR ?? '/etc/systemd/system';
const record = `${base}/permissions.json`;
const dropIn = `${unitDir}/airmouse.service.d/sensor.conf`;
const mode = process.argv[2] ?? 'start';
if (!['prepare', 'start', 'restore'].includes(mode)) throw new Error('Unknown permissions mode');
const root = fs.realpathSync(Sensor.discover());
const device = `/dev/${path.basename(root)}`;
const files = [...ownedSettings.map(k => `${root}/${k}`), device];
const sandbox = `# Generated by runtime/permissions.mjs from sensor discovery; do not edit.\n[Service]\nReadWritePaths=${root}\nDeviceAllow=${device} r\n`;

if (mode === 'restore') {
  if (fs.existsSync(record)) {
    const original = readJSON(record);
    if (original.root !== root) throw new Error('Sensor path changed; inspect saved permissions');
    for (const f of original.files) { fs.chownSync(f.path, f.uid, f.gid); fs.chmodSync(f.path, f.mode); }
    fs.unlinkSync(record);
  }
  fs.rmSync(dropIn, { force: true });
} else {
  for (const pid of fs.readdirSync('/proc').filter(p => /^\d+$/.test(p))) {
    let fds; try { fds = fs.readdirSync(`/proc/${pid}/fd`); } catch { continue; }
    for (const fd of fds) {
      let target; try { target = fs.readlinkSync(`/proc/${pid}/fd/${fd}`); } catch { continue; }
      if (target === device || files.includes(target)) throw new Error(`Sensor is open by PID ${pid}`);
    }
  }
  const original = fs.existsSync(record) ? readJSON(record) : { root, files: [] };
  if (original.root !== root) throw new Error('Sensor path changed; inspect saved permissions');
  const missing = files.filter(p => !original.files.some(f => f.path === p));
  for (const p of missing) {
    const s = fs.statSync(p);
    original.files.push({ path: p, uid: s.uid, gid: s.gid, mode: s.mode & 0o777 });
  }
  if (missing.length) saveJSON(record, original);
  const gid = Number(execFileSync('id', ['-g', 'airmouse'], { encoding: 'utf8' }).trim());
  for (const file of files) { fs.chownSync(file, 0, gid); fs.chmodSync(file, 0o660); }
  const current = fs.existsSync(dropIn) ? fs.readFileSync(dropIn, 'utf8') : '';
  if (mode === 'prepare') {
    if (current !== sandbox) { fs.mkdirSync(path.dirname(dropIn), { recursive: true }); fs.writeFileSync(dropIn, sandbox, { mode: 0o644 }); }
  } else if (current !== sandbox) {
    throw new Error(`Sensor sandbox drop-in does not match the discovered sensor ${root}; run the installer again`);
  }
}
