#ifndef AIRMOUSE_BTSTACK_CONFIG_H
#define AIRMOUSE_BTSTACK_CONFIG_H
#define HAVE_ASSERT
#define HAVE_MALLOC
#define HAVE_POSIX_FILE_IO
#define HAVE_POSIX_TIME
#define ENABLE_BLE
#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_SECURE_CONNECTIONS
#define ENABLE_LE_PRIVACY_ADDRESS_RESOLUTION
#define ENABLE_LE_DATA_LENGTH_EXTENSION
#define ENABLE_MICRO_ECC_FOR_LE_SECURE_CONNECTIONS
#define ENABLE_SOFTWARE_AES128
#define ENABLE_LOG_ERROR
#define MAX_NR_HCI_CONNECTIONS 1
#define HCI_ACL_PAYLOAD_SIZE (251 + 4)
#define NVM_NUM_DEVICE_DB_ENTRIES 4
#endif
