#!/usr/bin/env python3
"""Fake service manager and device-only commands for installer transaction tests."""
import json
import os
import pathlib
import sys

command = pathlib.Path(sys.argv[0]).name
args = sys.argv[1:]
base = pathlib.Path(os.environ['AIRMOUSE_BASE'])
state_file = base / 'fake-systemd.json'
state = json.loads(state_file.read_text())

def save():
    state_file.write_text(json.dumps(state))

def fail_at(point):
    marker = base / 'injected-failure'
    if os.environ.get('INSTALL_FAIL') == point and not marker.exists():
        marker.touch()
        sys.exit(1)

with (base / 'commands.log').open('a') as log:
    log.write(command + ' ' + ' '.join(args) + '\n')

if command == 'id':
    sys.exit(0)
elif command == 'chown':
    if any(arg.endswith('bluetooth-journal.json') for arg in args):
        fail_at('journal-ownership')
elif command == 'node':
    if args[0] == '--check':
        fail_at('syntax')
    elif args[0].endswith('permissions.mjs'):
        fail_at('permissions')
        if 'prepare' in args:
            drop_in = pathlib.Path(os.environ['AIRMOUSE_UNIT_DIR']) / 'airmouse.service.d' / 'sensor.conf'
            drop_in.parent.mkdir(parents=True, exist_ok=True)
            drop_in.write_text('generated by new release')
    elif args[0].endswith('bluetooth-journal.mjs'):
        fail_at('journal')
        (base / 'state/bluetooth-journal.json').write_text('{}')
    elif args[0].endswith('ready.mjs'):
        fail_at('readiness')
elif command == 'systemctl':
    action = args[0]
    if action == 'is-active':
        sys.exit(0 if state['active'] else 3)
    elif action == 'is-enabled':
        sys.exit(0 if state['enabled'] else 1)
    elif action == 'stop':
        fail_at('stop')
        state['active'] = False
    elif action in ['enable', 'disable']:
        state['enabled'] = action == 'enable'
        if '--now' in args:
            state['active'] = state['enabled']
            save()
            fail_at('start')
    elif action == 'start':
        state['active'] = True
        save()
        fail_at('start')
    save()
else:
    raise RuntimeError('Unexpected fixture command: ' + command)
